argocd:
  namespace: argocd
project: default
destination:
  name: in-cluster
domain: ""
credentialsSecret: runai-cluster-credentials
runai:
  namespace: runai
  version: ""
customCAName: ""
selfSignedCA: false
caBundleName: runai-ca-bundle
