name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.0

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Bake chart repo URL and version into runai values
        run: |
          CHART_REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          CHART_VERSION="$(yq '.version' runai/Chart.yaml)"
          yq -i "
            .chartRepo.url = \"${CHART_REPO_URL}\" |
            .chartRepo.revision = \"${CHART_VERSION}\"
          " runai/values.yaml

      - name: Add chart repositories
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
